# Generated by Django 5.1 on 2024-08-26 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkuploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='chunks_received',
        ),
    ]
