# Generated by Django 5.1 on 2024-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkuploader', '0002_remove_uploadedfile_chunks_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='chunks_received',
            field=models.IntegerField(default=0),
        ),
    ]
