# Generated by Django 5.1 on 2024-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunkuploader', '0003_uploadedfile_chunks_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
