# Generated by Django 5.1 on 2024-08-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunkuploader', '0004_uploadedfile_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_complete',
        ),
    ]
